# Reusable workflow to run Sphinx linkcheck on docs via Pixi

name: pixi-sphinx-linkcheck

on:
  workflow_call:

jobs:
  sphinx-linkcheck:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e
        with:
          pixi-version: v0.62.2
          cache: true

      - name: linkcheck docs
        run: pixi run linkcheck
